-- ============================================================
-- ATLANTIC ROLEPLAY EMS — SECURITY HARDENING
-- Supabase SQL Editor:  https://supabase.com/dashboard/project/tumrzwermkicjuvzlisi/sql/new
--
-- Apply AFTER supabase-schema.sql + supabase-roles.sql.
-- Safe to re-run (idempotent).
--
-- CONTENTS
--   (1) Ban is enforced at the database level for PATIENT writes:
--       a suspended account cannot create new comments, contact
--       messages, joining applications, medication requests or
--       appointments (it can still read its own history).
--   (2) Promo code usage limit claim is ATOMIC (row locked + guarded
--       increment), closing a race where two concurrent orders could
--       overshoot max_uses.
--   (3) Storage bucket access is restricted to the expected folder
--       layout and file types, as defense-in-depth on top of the
--       high-entropy document codes (now generated by my-space.js).
-- ============================================================

-- ============================================================
-- (1) BAN-ENFORCED PATIENT WRITE POLICIES
-- A suspended account keeps read access to its own history but is
-- blocked from creating new content. Staff access was already
-- blocked inside authorize() / the SECURITY DEFINER RPCs.
-- ============================================================

DROP POLICY IF EXISTS "comments_insert_own" ON public.comments;
CREATE POLICY "comments_insert_own"
  ON public.comments FOR INSERT TO authenticated
  WITH CHECK (account_id IN (SELECT account_id FROM public.accounts
             WHERE id = auth.uid() AND is_banned IS NOT TRUE));

DROP POLICY IF EXISTS "contacts_insert_own" ON public.contacts;
CREATE POLICY "contacts_insert_own"
  ON public.contacts FOR INSERT TO authenticated
  WITH CHECK (account_id IN (SELECT account_id FROM public.accounts
             WHERE id = auth.uid() AND is_banned IS NOT TRUE));

DROP POLICY IF EXISTS "applications_insert_own" ON public.applications;
CREATE POLICY "applications_insert_own"
  ON public.applications FOR INSERT TO authenticated
  WITH CHECK (account_id IN (SELECT account_id FROM public.accounts
             WHERE id = auth.uid() AND is_banned IS NOT TRUE));

DROP POLICY IF EXISTS "med_requests_insert_own" ON public.medication_requests;
CREATE POLICY "med_requests_insert_own"
  ON public.medication_requests FOR INSERT TO authenticated
  WITH CHECK (discord_id IN (SELECT account_id FROM public.accounts
             WHERE id = auth.uid() AND is_banned IS NOT TRUE));

DROP POLICY IF EXISTS "appointments_insert_own" ON public.medical_appointments;
CREATE POLICY "appointments_insert_own"
  ON public.medical_appointments FOR INSERT TO authenticated
  WITH CHECK (discord_id IN (SELECT account_id FROM public.accounts
             WHERE id = auth.uid() AND is_banned IS NOT TRUE));

-- ============================================================
-- (2) ATOMIC PROMO USAGE-LIMIT CLAIM
-- Replaces compute_med_request_pricing so that the promo row is
-- locked with SELECT ... FOR UPDATE and used_count is incremented
-- only when it is still below max_uses. Concurrent orders can no
-- longer overshoot the limit.
-- ============================================================
CREATE OR REPLACE FUNCTION public.compute_med_request_pricing()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  med     medications%ROWTYPE;
  promo   promo_codes%ROWTYPE;
  claimed integer;
BEGIN
  SELECT * INTO med FROM medications WHERE id = NEW.medication_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Medication not found.';
  END IF;
  IF NOT med.is_available OR med.stock <= 0 THEN
    RAISE EXCEPTION 'This medication is currently unavailable.';
  END IF;
  IF NEW.quantity IS NULL OR NEW.quantity < 1 OR NEW.quantity > 999 THEN
    RAISE EXCEPTION 'Invalid quantity.';
  END IF;

  NEW.medication_name := med.name;
  NEW.unit_price      := med.price;
  NEW.original_price  := med.price * NEW.quantity;
  NEW.discount_amount := 0;
  NEW.status          := 'PENDING';

  IF COALESCE(NEW.promo_code, '') <> '' THEN
    SELECT * INTO promo FROM promo_codes
     WHERE upper(code) = upper(NEW.promo_code)
     FOR UPDATE;
    IF NOT FOUND OR NOT promo.is_active
       OR (promo.expires_at IS NOT NULL AND promo.expires_at < now()) THEN
      RAISE EXCEPTION 'Invalid promo code.';
    END IF;

    -- Claim one use atomically: only if the limit is not reached yet.
    IF promo.max_uses IS NOT NULL THEN
      UPDATE promo_codes
         SET used_count = used_count + 1
       WHERE id = promo.id AND used_count < promo.max_uses;
      GET DIAGNOSTICS claimed = ROW_COUNT;
      IF claimed = 0 THEN
        RAISE EXCEPTION 'This promo code has reached its usage limit.';
      END IF;
    ELSE
      UPDATE promo_codes SET used_count = used_count + 1 WHERE id = promo.id;
    END IF;

    IF promo.discount_type = 'fixed' THEN
      NEW.discount_amount := LEAST(promo.discount_value, NEW.original_price);
    ELSE
      NEW.discount_amount := ROUND(NEW.original_price * promo.discount_value / 100, 2);
    END IF;
    NEW.promo_code := promo.code;
  END IF;

  NEW.final_price := GREATEST(NEW.original_price - NEW.discount_amount, 0);
  NEW.updated_at  := now();
  IF NEW.created_at IS NULL THEN NEW.created_at := now(); END IF;
  RETURN NEW;
END;
$$;

-- ============================================================
-- (3) STORAGE — PATH + TYPE WHITELIST (defense-in-depth)
-- Signed URLs (SELECT) are only possible for files under the
-- expected folder layout, and uploads (INSERT) are limited to
-- document file types. Combined with the high-entropy document
-- codes, other patients' files cannot be enumerated.
-- ============================================================

DROP POLICY IF EXISTS "doc_objects_select_auth" ON storage.objects;
CREATE POLICY "doc_objects_select_auth"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'medical-documents'
         AND COALESCE((storage.foldername(name))[1], '') IN ('tests', 'certificates'));

DROP POLICY IF EXISTS "doc_objects_insert_staff" ON storage.objects;
CREATE POLICY "doc_objects_insert_staff"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'medical-documents'
              AND (public.authorize('EMS') OR public.authorize('Manager'))
              AND COALESCE((storage.foldername(name))[1], '') IN ('tests', 'certificates')
              AND lower(storage.extension(name)) IN ('pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp'));

-- ============================================================
-- FINAL CHECK
-- ============================================================
-- SELECT tablename FROM pg_policies WHERE schemaname IN ('public','storage')
--    AND policyname IN ('comments_insert_own','contacts_insert_own',
--      'applications_insert_own','med_requests_insert_own',
--      'appointments_insert_own','doc_objects_select_auth',
--      'doc_objects_insert_staff') ORDER BY 1;
